'use client';

import { useActionState } from 'react';
import { createBook, type UploadState } from './actions';

const initialState: UploadState = {};

export function UploadForm() {
  const [state, action, pending] = useActionState(createBook, initialState);
  return <form action={action} className="mt-8 space-y-5"><div><label htmlFor="title" className="mb-2 block text-sm font-medium">Book title</label><input id="title" name="title" required className="w-full rounded-xl border border-[#d6d2c9] bg-white px-4 py-3 outline-none focus:border-[#b64d2d]" /></div><div><label htmlFor="author_name" className="mb-2 block text-sm font-medium">Author name</label><input id="author_name" name="author_name" required className="w-full rounded-xl border border-[#d6d2c9] bg-white px-4 py-3 outline-none focus:border-[#b64d2d]" /></div><div><label htmlFor="description" className="mb-2 block text-sm font-medium">Description</label><textarea id="description" name="description" required minLength={20} rows={5} className="w-full rounded-xl border border-[#d6d2c9] bg-white px-4 py-3 outline-none focus:border-[#b64d2d]" /></div><div><label htmlFor="price" className="mb-2 block text-sm font-medium">Price in Nigerian naira</label><input id="price" name="price" type="number" min="0" step="0.01" defaultValue="0" className="w-full rounded-xl border border-[#d6d2c9] bg-white px-4 py-3 outline-none focus:border-[#b64d2d]" /></div><label className="flex items-center gap-3 text-sm"><input name="is_free" type="checkbox" className="h-4 w-4 accent-[#b64d2d]" /> This book is free</label><div><label htmlFor="cover" className="mb-2 block text-sm font-medium">Cover image <span className="font-normal text-[#817e74]">(optional, 10 MB max)</span></label><input id="cover" name="cover" type="file" accept="image/*" className="block w-full text-sm text-[#62645d] file:mr-4 file:rounded-lg file:border-0 file:bg-[#dfe8df] file:px-4 file:py-2 file:font-semibold" /></div><div><label htmlFor="pdf" className="mb-2 block text-sm font-medium">PDF book <span className="font-normal text-[#817e74]">(required, 20 MB max)</span></label><input id="pdf" name="pdf" type="file" accept="application/pdf,.pdf" required className="block w-full text-sm text-[#62645d] file:mr-4 file:rounded-lg file:border-0 file:bg-[#dfe8df] file:px-4 file:py-2 file:font-semibold" /></div>{state.error && <p role="alert" className="rounded-xl bg-[#fbe9e3] px-4 py-3 text-sm leading-6 text-[#8d321d]">{state.error}</p>}<button type="submit" disabled={pending} className="w-full rounded-xl bg-[#20211f] px-4 py-3.5 text-sm font-semibold text-white hover:bg-[#b64d2d] disabled:opacity-60">{pending ? 'Uploading...' : 'Save book as draft'}</button></form>;
}
